---
api: https://vcd.vchs.vmware.com
username: username
password: ******
entities:
    organization: VDC-name
    virtual_datacenter: VDC-name
    vapp_catalog: vapp-cat-name
    media_catalog: media-cat-name
control:
    retries:
        default: 1
        upload_vapp_files: 1
    time_limit_sec:
        http_request: 60
    rest_throttle:
        min: 0
        max: 2
