---
url: https://vcd.vchs.vmware.com
user: username
password: ******
entities:
    organization: org-name
    virtual_datacenter: VDC-name
    vapp_catalog: vapp-cat-name
    media_catalog: media-cat-name
    vm_metadata_key: agent-env
