---
url: https://vcd.vchs.vmware.com
user: username
password: ******
entities:
    organization: VDC-name
    virtual_datacenter: VDC-name
    vapp_catalog: vapp-cat-name
    media_catalog: media-cat-name
control:
    retries:
        default: 1
        upload_vapp_files: 1
    time_limit_sec:
        default: 300
        http_request: 60
        process_descriptor_vapp_template: 300
    rest_throttle:
        min: 0
        max: 2
    delay: 10
    backoff: 1
